### ISSUE TITLE
Adding argument "--version" and "-u" to specify user agent

### ISSUE THREAD

**Issue by jongwon-jang** [jiyoungsin/OSD_A1_Tool#6]
Realized only "-v" works. I will add --version as well

I will also try to implement this optional feature:
add a command line flag to allow specifying a custom User Agent string when doing network requests.

Thank you :)

**Comment by jiyoungsin** [comment]
Thank you for letting me know jongwon-jang! Please have a go!

**Comment by jiyoungsin** [comment]
Hey jongwon, thanks for the pull request. It seems like the --version works great! however, I am still having troubles understanding how the user-agent works and how it will help. Can you please clarify this for me?

**Comment by jiyoungsin** [comment]
I figured it out! user-agents are like specific browsers.
